# create a file config.ini in the same directory with the following content:

[default]
bootstrap.servers=< Endpoint >
security.protocol=SASL_SSL
sasl.mechanisms=PLAIN
sasl.username=< API Key >
sasl.password=< API Secret >

[producer]
linger.ms=5
acks=all
compression.type=lz4

[consumer]
group.id=< Consumer Group ID >
# 'auto.offset.reset=earliest' to start reading from the beginning of
# the topic if no committed offsets exist.
auto.offset.reset=earliest