# Generated by Django 6.0.3 on 2026-03-19 09:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sql_command', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('connection_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit_events', to='connections.connectionprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commit_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InverseOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.CharField(db_index=True, max_length=255)),
                ('inverse_sql', models.TextField()),
                ('commit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inverse_operation', to='core.commitevent')),
            ],
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('version_id', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('s3_key', models.CharField(max_length=500)),
                ('connection_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='connections.connectionprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('connection_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot_policy', to='connections.connectionprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='commitevent',
            index=models.Index(fields=['user', 'timestamp'], name='core_commit_user_id_bfb1fc_idx'),
        ),
    ]
