# Generated by Django 6.0.3 on 2026-03-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_commitevent_seq'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commitevent',
            new_name='core_commit_connect_510719_idx',
            old_name='core_commit_connprofile_seq_idx',
        ),
    ]
