# Generated by Django 6.0.3 on 2026-04-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_core_commit_connprofile_seq_idx_core_commit_connect_510719_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitevent',
            name='commit_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
